/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package databasetonewsletter;

import java.awt.Container;

/**
 *
 * @author Majitel
 */
public class JPanelConection extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConection
     */
    
    
    Container container;
    
    public JPanelConection(Container container) {
        initComponents();
        this.container = container;
        setT();
    }
    
    public void setT(){
        if(WorkerDatabase.online) {
            this.conection.setText("přejít do režimu offline");
            //this.refresh.setVisible(true);
        } else {
            this.conection.setText("přejít do režimu online");
            //this.refresh.setVisible(false);
        }
    }
    @Override
    public void  revalidate(){       
        
        if((conection != null )){
        setT();
        }  
        //super.repaint();
        super.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conection = new javax.swing.JButton();

        conection.setText("přejít do režimu online");
        conection.setToolTipText("");
        conection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(conection, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(conection, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void conectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectionActionPerformed
        if(WorkerDatabase.online) {
            WorkerDatabase.saveDatabase();
            WorkerDatabase.setOfflineDatabase();
            WorkerDatabase.online = false;
            revalidate();
            repaint();
        } else {
           JFrameConect conect = new JFrameConect(container);
            
        }
        
    }//GEN-LAST:event_conectionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conection;
    // End of variables declaration//GEN-END:variables
}
