/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package databasetonewsletter;

import javax.swing.JRadioButton;

/**
 *
 * @author Majitel
 */
public class JPanelMenulButtonBottom extends javax.swing.JPanel {

    /**
     * Creates new form JPanelMenulButtonBottom
     */
    JFrameMenu frameMenu;
    public JPanelMenulButtonBottom(JFrameMenu frameMenu) {
        initComponents();
        this.frameMenu = frameMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        selectCancel = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        selectAll = new javax.swing.JButton();
        eneblePrint = new javax.swing.JButton();
        disablePrint = new javax.swing.JButton();
        selectToNotPrinted = new javax.swing.JButton();
        selectToPrinted = new javax.swing.JButton();

        jButton4.setText("jButton1");

        selectCancel.setText("zrušit výběr");
        selectCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCancelActionPerformed(evt);
            }
        });

        delete.setText("smazat");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        selectAll.setText("vybrat vše");
        selectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllActionPerformed(evt);
            }
        });

        eneblePrint.setText("přidat k tisku");
        eneblePrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eneblePrintActionPerformed(evt);
            }
        });

        disablePrint.setText("odstranit z tisku");
        disablePrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disablePrintActionPerformed(evt);
            }
        });

        selectToNotPrinted.setText("<html>vybrat </br> k nevytištění</html>");
        selectToNotPrinted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectToNotPrintedActionPerformed(evt);
            }
        });

        selectToPrinted.setText("<html>vybrat</br> k vytištění</html>");
        selectToPrinted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectToPrintedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectAll, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectToPrinted, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectToNotPrinted, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(selectCancel)
                .addGap(85, 85, 85)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(eneblePrint)
                .addGap(39, 39, 39)
                .addComponent(disablePrint)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(disablePrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(eneblePrint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectToPrinted)
                            .addComponent(selectToNotPrinted))
                        .addComponent(selectAll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectCancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllActionPerformed
        for (int i = 0; i < frameMenu.menuLines.jrb.size(); i++) {
                JRadioButton button =frameMenu.menuLines.jrb.get(i);
                button.setSelected(true);
                button.revalidate();
        }
    }//GEN-LAST:event_selectAllActionPerformed

    private void selectCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCancelActionPerformed
        for (int i = 0; i < frameMenu.menuLines.jrb.size(); i++) {
                JRadioButton button =frameMenu.menuLines.jrb.get(i);
                button.setSelected(false);
                button.revalidate();
        }
    }//GEN-LAST:event_selectCancelActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
         for (JRadioButtonWithNumber button  :frameMenu.menuLines.jrb) {
                if(button.isSelected()){                   
                    frameMenu.database.nowWorkDatabase.removeElement(button.element);
                }
        }
        frameMenu.menuLines.overWritePanel();
    }//GEN-LAST:event_deleteMouseClicked

    private void eneblePrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eneblePrintActionPerformed
         for (JRadioButtonWithNumber button  :frameMenu.menuLines.jrb) {
                if(button.isSelected()){                   
                    button.element.setStringPrinted(true);
                    
                }
        }
        frameMenu.menuLines.overWritePanel();
    }//GEN-LAST:event_eneblePrintActionPerformed

    private void disablePrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disablePrintActionPerformed
        for (JRadioButtonWithNumber button  :frameMenu.menuLines.jrb) {
                if(button.isSelected()){                   
                    button.element.setStringPrinted(false);
                }
        }
        frameMenu.menuLines.overWritePanel();
    }//GEN-LAST:event_disablePrintActionPerformed

    private void selectToNotPrintedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectToNotPrintedActionPerformed
         for (JRadioButtonWithNumber button  :frameMenu.menuLines.jrb) {
                if(!button.element.isPrinted()){                   
                    button.setSelected(true);
                    button.revalidate();
                }
        } 
        
         
    }//GEN-LAST:event_selectToNotPrintedActionPerformed

    private void selectToPrintedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectToPrintedActionPerformed
        
        for (JRadioButtonWithNumber button  :frameMenu.menuLines.jrb) {
                if(button.element.isPrinted()){                   
                    button.setSelected(true);
                    button.revalidate();
                }
        } 
   
    }//GEN-LAST:event_selectToPrintedActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton disablePrint;
    private javax.swing.JButton eneblePrint;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton selectAll;
    private javax.swing.JButton selectCancel;
    private javax.swing.JButton selectToNotPrinted;
    private javax.swing.JButton selectToPrinted;
    // End of variables declaration//GEN-END:variables
}
